"""update CourseManager

Revision ID: 0fbf4a88e02a
Revises: c7a68156ba40
Create Date: 2021-03-06 21:35:37.318945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbf4a88e02a'
down_revision = 'c7a68156ba40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('course_managers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_managers',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_present', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='course_managers_course_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='course_managers_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'course_id', name='course_managers_pkey')
    )
    op.drop_table('course_manager')
    # ### end Alembic commands ###
