"""empty message

Revision ID: 229dc69d3c00
Revises: 62ecd3c31b0a
Create Date: 2021-02-11 13:51:40.034286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229dc69d3c00'
down_revision = '62ecd3c31b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('reputation', sa.Float()))
    op.add_column('version', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('version', 'is_accepted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('version', sa.Column('is_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('version', 'status')
    op.drop_column('user', 'reputation')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
