"""empty message

Revision ID: 81fd47a66c03
Revises: 9cf681785362
Create Date: 2021-02-07 08:14:38.772164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fd47a66c03'
down_revision = '9cf681785362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('chapter', 'chapter_name')
    op.add_column('course', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint('course_course_name_key', 'course', type_='unique')
    op.create_unique_constraint(None, 'course', ['name'])
    op.drop_column('course', 'course_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('course_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'course', type_='unique')
    op.create_unique_constraint('course_course_name_key', 'course', ['course_name'])
    op.drop_column('course', 'name')
    op.add_column('chapter', sa.Column('chapter_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('chapter', 'name')
    # ### end Alembic commands ###
