"""empty message

Revision ID: a5b96f01ad6f
Revises: 229dc69d3c00
Create Date: 2021-02-11 15:07:57.950937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b96f01ad6f'
down_revision = '229dc69d3c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('version', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'version', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'version', type_='foreignkey')
    op.drop_column('version', 'course_id')
    # ### end Alembic commands ###
