"""empty message

Revision ID: b5a136714f6f
Revises: b89d220a834f
Create Date: 2021-02-08 09:30:06.572202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a136714f6f'
down_revision = 'b89d220a834f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chapter_next_chapter_id_fkey', 'chapter', type_='foreignkey')
    op.drop_column('chapter', 'next_chapter_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('next_chapter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chapter_next_chapter_id_fkey', 'chapter', 'chapter', ['next_chapter_id'], ['id'])
    # ### end Alembic commands ###
