"""empty message

Revision ID: b89d220a834f
Revises: 81fd47a66c03
Create Date: 2021-02-07 09:44:14.855804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89d220a834f'
down_revision = '81fd47a66c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'notes')
    # ### end Alembic commands ###
