"""update Course manager

Revision ID: dc2cf08a3dd4
Revises: e03b1c14f035
Create Date: 2021-03-07 13:25:54.361621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2cf08a3dd4'
down_revision = 'e03b1c14f035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_manager')
    op.add_column('course', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'user', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'manager_id')
    op.create_table('course_manager',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_present', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='course_manager_pkey')
    )
    # ### end Alembic commands ###
