"""update CourseManager

Revision ID: e03b1c14f035
Revises: 0fbf4a88e02a
Create Date: 2021-03-06 21:43:30.617768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03b1c14f035'
down_revision = '0fbf4a88e02a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_manager', sa.Column('is_present', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_manager', 'is_present')
    # ### end Alembic commands ###
